ConexaoMongo/PetMongoDB/PetMongoDB/Models/ContextMongoDB.cs
using MongoDB.Bson;
using MongoDB.Bson.Serialization;
using MongoDB.Bson.Serialization.Serializers;
using MongoDB.Driver;

namespace PetMongoDB.Models
{
    public class ContextMongoDB
    {
        public static string? ConnectionString { get; set; }
        public static string? Database { get; set; }
        //camada de segurança (true or false) por isso é booleano
        public static bool IsSSL { get; set; }
        public IMongoDatabase _database { get; }

        static ContextMongoDB()
        {
            BsonSerializer.RegisterSerializer(new GuidSerializer(GuidRepresentation.Standard));
        }
        public ContextMongoDB()
        {
            try
            {
                MongoClientSettings settings = MongoClientSettings.FromUrl(new MongoUrl(ConnectionString));
                if(IsSSL)
                {
                    //verificação
                    settings.SslSettings = new SslSettings { EnabledSslProtocols = System.Security.Authentication.SslProtocols.Tls12 };
                }
                //instancinado um objeto que será criado nessa váriavel
                var mongoCliente = new MongoClient(settings);
                _database = mongoCliente.GetDatabase(Database);

            }
            //criando uma excessão genérica
            catch(Exception)
            {
                throw new Exception("Não foi possível conectar ao MongoDB");

            }
        }//conexão mongo

        //criando a classe Pet no Mongo
        public IMongoCollection <Pet> Pet
        {
             get
            {
                return _database.GetCollection<Pet>("Pet");
            }
        }

    }//fim classe

}//fim namespace

ConexaoMongo/PetMongoDB/PetMongoDB/Models/ErrorViewModel.cs
namespace PetMongoDB.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ConexaoMongo/PetMongoDB/PetMongoDB/Models/Pet.cs
namespace PetMongoDB.Models
{
    public class Pet
    {
        //usando um tipo Guid usado para chave que tenha números e letras 
        public Guid Id { get; set; }
        public string ? Nome { get; set; }
        public int Idade { get; set; }
        public string? Raca { get; set; }
        //Inserindo as info do cuidador do pet
        public string? Cuidador { get; set; }
        public string? Celular { get; set; }


    }
}

ConexaoMongo/PetMongoDB/PetMongoDB/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using PetMongoDB.Models;

namespace PetMongoDB.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

ConexaoMongo/PetMongoDB/PetMongoDB/Controllers/PetsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MongoDB.Driver;
using PetMongoDB.Data;
using PetMongoDB.Models;

namespace PetMongoDB.Controllers
{
    public class PetsController : Controller
    {
        //criando uma vpáriavel de contexto 
        ContextMongoDB _context = new ContextMongoDB();

        // GET: Pets
        public async Task<IActionResult> Index()
        {
            //mudando depois do find
            return View(await _context.Pet.Find(u => true).ToListAsync());
        }

        // GET: Pets/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //mudanças para que ele procure na coleçõa um ID
            var pet = await _context.Pet
                .Find(m => m.Id == id).FirstOrDefaultAsync();
            if (pet == null)
            {
                return NotFound();
            }

            return View(pet);
        }

        // GET: Pets/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Pets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Idade,Raca,Cuidador,Celular")] Pet pet)
        {
            if (ModelState.IsValid)
            {
                
                pet.Id = Guid.NewGuid();
                //mudança feita: retirou as duas linhas do meio e inseriu uma nova linha
                await _context.Pet.InsertOneAsync(pet);
                return RedirectToAction(nameof(Index));
            }
            return View(pet);
        }

        // GET: Pets/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //substituindo a sentença antiga para essa nova(copiada do Details)
            var pet = await _context.Pet
               .Find(m => m.Id == id).FirstOrDefaultAsync();
            if (pet == null)
            {
                return NotFound();
            }
            return View(pet);
        }

        // POST: Pets/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Nome,Idade,Raca,Cuidador,Celular")] Pet pet)
        {
            if (id != pet.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    //mudança feita, mandando ir na coleção pet e achar o documentos em que o id do pet bata com este ID
                    await _context.Pet.ReplaceOneAsync(m => m.Id == pet.Id, pet);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PetExists(pet.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pet);
        }

        // GET: Pets/Delete/5
        //buscando o que vocês querem deletar
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //mudança feita colando o mesmo feito no details
            var pet = await _context.Pet
                 .Find(m => m.Id == id).FirstOrDefaultAsync();
            if (pet == null)
            {
                return NotFound();
            }

            return View(pet);
        }

        // POST: Pets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            //mudança feita
            await _context.Pet.DeleteOneAsync(u => u.Id == id);
            return RedirectToAction(nameof(Index));
        }

        private bool PetExists(Guid id)
        {
            //mudança feita
            return _context.Pet.Find(e => e.Id == id).Any();
        }
    }
}

ConexaoMongo/PetMongoDB/PetMongoDB/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ConexaoMongo/PetMongoDB/PetMongoDB/Views/Pets/Create.cshtml
@model PetMongoDB.Models.Pet

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Pet</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Idade" class="control-label"></label>
                <input asp-for="Idade" class="form-control" />
                <span asp-validation-for="Idade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Raca" class="control-label"></label>
                <input asp-for="Raca" class="form-control" />
                <span asp-validation-for="Raca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cuidador" class="control-label"></label>
                <input asp-for="Cuidador" class="form-control" />
                <span asp-validation-for="Cuidador" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Celular" class="control-label"></label>
                <input asp-for="Celular" class="form-control" />
                <span asp-validation-for="Celular" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ConexaoMongo/PetMongoDB/PetMongoDB/Views/Pets/Delete.cshtml
@model PetMongoDB.Models.Pet

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pet</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Idade)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Idade)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Raca)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Raca)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cuidador)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cuidador)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Celular)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Celular)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ConexaoMongo/PetMongoDB/PetMongoDB/Views/Pets/Details.cshtml
@model PetMongoDB.Models.Pet

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Pet</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Idade)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Idade)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Raca)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Raca)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cuidador)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cuidador)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Celular)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Celular)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ConexaoMongo/PetMongoDB/PetMongoDB/Views/Pets/Edit.cshtml
@model PetMongoDB.Models.Pet

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Pet</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Idade" class="control-label"></label>
                <input asp-for="Idade" class="form-control" />
                <span asp-validation-for="Idade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Raca" class="control-label"></label>
                <input asp-for="Raca" class="form-control" />
                <span asp-validation-for="Raca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cuidador" class="control-label"></label>
                <input asp-for="Cuidador" class="form-control" />
                <span asp-validation-for="Cuidador" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Celular" class="control-label"></label>
                <input asp-for="Celular" class="form-control" />
                <span asp-validation-for="Celular" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ConexaoMongo/PetMongoDB/PetMongoDB/Views/Pets/Index.cshtml
@model IEnumerable<PetMongoDB.Models.Pet>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Idade)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Raca)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cuidador)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Celular)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Idade)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Raca)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cuidador)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Celular)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

ConexaoMongo/PetMongoDB/PetMongoDB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PetMongoDB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PetMongoDB.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PetMongoDB</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @* criando um link dos pets *@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pets" asp-action="Index">Pets</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - PetMongoDB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>